export { Plus } from './plus'
export { MagnifyingGlass } from './magnifying-glass'
export { ChevronLeft } from './chevron-left'
export { Movie } from './movie'
export { Link } from './link'
export { TV } from './tv'
export { Star } from './star'
